Map<String, List<String>> statesAndBranches = {
  'Selangor': [
    'AGROBANK KAJANG',
    'AGROBANK TELOK PANGLIMA GARANG',
    'AGROBANK SEMENYIH',
    'AGROBANK SUBANG JAYA',
    'AGROBANK GREENWOOD',
    'AGROBANK SALAK TINGGI',
    'AGROBANK AMPANG JAYA',
    'AGROBANK TANJUNG KARANG',
    'AGROBANK PUTRAJAYA',
    'AGROBANK JERAM',
    'AGROBANK SUNGAI BEASR'
  ],
  'Kuala Lumpur': [
    'AGROBANK AMPANG POINT',
    'AGROBANK CHERAS',
    'AGROBANK BANDAR TASIK SELATAN',
    'AGROBANK SELAYANG',
    'AGROBANK SUNGAI BULOH',
    'AGROBANK SHAH ALAM',
    'AGROBANK PUTRAJAYA',
    'AGROBANK SEMENYIH',
    'AGROBANK KLANG',
    'AGROBANK KUALA SELANGOR',
    'AGROBANK SALAK TINGGI',
    'AGROBANK TELUK PANGLIMA GARANG',
    'AGROBANK BANTING'
  ],
  'Pahang': [
    'AGROBANK BENTONG',
    'AGROBANK RAUB',
    'AGROBANK SUNGAI RUAN',
    'AGROBANK CAMERON HIGHLAND',
    'AGROBANK JENGKA',
    'AGROBANK JERANTUT',
    'AGROBANK TEMERLOH',
    'AGROBANK TRIANG',
    'AGROBANK LANCHANG',
    'AGROBANK MARAN',
    'AGROBANK KUALA ROMPIN'
  ],
  'Perak': [
    'AGROBANK TANJUNG MALIM',
    'AGROBANK SLIM RIVER',
    'AGROBANK SRI ISKANDAR',
    'AGROBANK TELUK INTAN',
    'AGROBANK KUALA KANGSAR',
    'AGROBANK PANTAI REMIS',
    'AGROBANK BAGAN SERAI',
    'AGROBANK LENGGONG',
    'AGROBANK KAMPUNG GAJAH',
    'AGROBANK TAPAH',
    'AGROBANK KAMPAR',
    'AGROBANK PARIT',
    'AGROBANK TELUK PANGLIMA GARANG',
    'AGROBANK BANTING'
  ],
  'Penang': [
    'AGROBANK BALIK PULAU',
    'AGROBANK NIBONG TEBAL',
    'AGROBANK BUKIT MERTAJAM',
    'AGROBANK KEPALA BATAS'
  ],
  'Kelantan': [
    'AGROBANK TANAH MERAH',
    'AGROBANK JELI',
    'AGROBANK PASIR PUTEH',
    'AGROBANK TELUK INTAN',
    'AGROBANK KUALA KRAI',
    'AGROBANK ANGLE SITI KHADIJAH CENTRAL',
    'AGROBANK BAGAN PASIR MAS'
  ],
  'Perlis': [
    'AGROBANK KANGAR',
    'AGROBANK KUALA PERLIS',
    'AGROBANK SIMPANG AMPAT',
    'AGROBANK KODIANG'
  ],
  'Kedah': [
    'AGROBANK CAWANGAN KULIM',
    'AGROBANK @ SIK BRANCH',
    'AGROBANK @ BALING BRANCH',
    'AGROBANK PENDANG',
    'AGROBANK ALOR SETAR',
    'AGROBANK JITRA',
    'AGROBANK LANGKAWI',
    'AGROBANK GUAR CHEMPEDAK'
  ],
  'Terengganu': [
    'AGROBANK @ BUKIT PAYONG',
    'AGROBANK @ CHUKAI',
    'AGROBANK MARANG'
        'AGROBANK KUALA BERANG',
    'AGROBANK KUALA TERENGGANU',
    'AGROBANK JERTEH'
  ],
  'Melaka': [
    'AGROBANK Melaka',
    'Agrobank @ Jalan Merdeka',
  ],
  'Negeri Sembilan': [
    'AR-RAHNU AGROBANK',
    'AGROBANK NILAI',
    'AGROBANK PASIR PANJANG',
    'AGROBANK SEREMBAN',
    'AGROBANK BAHAU'
  ],
  'Johor': [
    'AGROBANK JOHOR BAHRU',
    'AGROBANK KOTA TINGGI',
    'AGROBANK SEGAMAT',
    'AGROBANK SIMPANG RENGAM',
    'AGROBANK MUAR',
    'AGROBANK TANGKAK',
    'AGROBANK PONTIAN',
    'AGROBANK KLUANG',
    'AGROBANK KULAI',
    'AGROBANK BATU PAHAT',
    'AGROBANK BUKIT GAMBIR'
  ],
};
